# Topic 2
Numpy VS python List

In [13]:
l= range(100000)

In [12]:
%time for i in range(1,10): r=[x*2 for x in l]

Wall time: 161 ms


In [14]:
import numpy as np

In [15]:
d= np.arange(100000)

In [16]:
%time for i in range(1,10): r= d*2 

Wall time: 7 ms


In [75]:
list = range(20000000)

In [81]:
%time for b in range(1,10):  c = [num *3 for num in list] # c ek varibal h aur is k sth nested 
                                                                #loop laga h 
     

Wall time: 34 s


In [82]:
import numpy as np

In [83]:
list2 = np.arange(2000000) 

In [86]:
%time for b in range(1,10): c = list2 *3

Wall time: 101 ms


# Topic 3
Multidimensional array objact

In [7]:
import numpy as np

In [10]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [12]:
arr2 = np.array([1,2,3], dtype=np.int32)

In [13]:
arr1.dtype

dtype('float64')

In [14]:
arr2.dtype

dtype('int32')

In [15]:
arr = np.array([1, 2, 3, 4, 5])

In [16]:
arr.dtype

dtype('int32')

In [17]:
f = arr.astype(np.float)

In [18]:
f.dtype

dtype('float64')

In [19]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [20]:
i = arr.astype(np.int)

In [21]:
i.dtype

dtype('int32')

In [79]:
import numpy as np
ar = np.array([ 3, -1, -2, 0, 12, 10], dtype = np.int)


In [80]:
ar.dtype

dtype('int32')

In [81]:
s = np.array(['6.2','-5.2','42'])          

In [82]:
s.dtype   #ye apply ni hwa

dtype('<U4')

In [83]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [84]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [69]:
s.astype(float)

array([ 6.2, -5.2, 42. ])

In [73]:
array = np.arange(10)

In [87]:
s = np.array ([.45, .12, .56, 1.2, .78], dtype = np.float)

In [88]:
i.astype(s.dtype)

array([ 3., -1., -2.,  0., 12., 10.])

In [89]:
empty_uint32 = np.empty(8, dtype='u4') #There are shorthand type code strings
                                        #you can also use to refer to a dtype:




In [90]:
empty_uint32


array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

# topic 4
Arithmetic With ndarry 

In [1]:
import numpy as np

In [3]:
a = np.random.rand((10))
a

array([0.97066378, 0.03265365, 0.65092088, 0.05989028, 0.14542433,
       0.7475336 , 0.66949971, 0.76037845, 0.78649793, 0.11743268])

In [4]:
b = np.random.randn((10))
b

array([ 0.76309509, -0.67919306, -0.72071055,  0.95307701, -1.39666013,
        1.07805675,  0.60434428, -0.25224248, -1.04452629,  0.45550396])

In [5]:
a+b

array([ 1.73375888, -0.64653941, -0.06978968,  1.01296729, -1.2512358 ,
        1.82559035,  1.27384399,  0.50813596, -0.25802836,  0.57293664])

In [6]:
a-b

array([ 0.20756869,  0.7118467 ,  1.37163143, -0.89318674,  1.54208446,
       -0.33052315,  0.06515543,  1.01262093,  1.83102422, -0.33807129])

In [7]:
2*a

array([1.94132757, 0.06530729, 1.30184175, 0.11978055, 0.29084865,
       1.4950672 , 1.33899942, 1.52075689, 1.57299587, 0.23486536])

In [8]:
1/b

array([ 1.31045267, -1.47233543, -1.38751958,  1.04923315, -0.7159938 ,
        0.92759495,  1.65468596, -3.96443924, -0.95737179,  2.19537058])

In [9]:
b>0

array([ True, False, False,  True, False,  True,  True, False, False,
        True])

In [10]:
a[a>0]

array([0.97066378, 0.03265365, 0.65092088, 0.05989028, 0.14542433,
       0.7475336 , 0.66949971, 0.76037845, 0.78649793, 0.11743268])

In [91]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [92]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [93]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [95]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [96]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [97]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [99]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
print(arr2)


[[ 0.  4.  1.]
 [ 7.  2. 12.]]


In [101]:
x = arr2 > arr
print(x)


[[False  True False]
 [ True False  True]]


In [102]:
print(x.dtype)

bool


# Topic 5
Indexing & Slicing

In [104]:
#Basic Indexing and Slicing
arr = np. arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
arr[4]

4

In [107]:
arr[5:8]

array([5, 6, 7])

In [108]:
arr[5:8] = 12

In [109]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [110]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [112]:
slice = arr[5:8]
slice

array([12, 12, 12])

In [122]:
arr_slice[1] = 12345
print(arr)
print(arr_slice)


[    0     1     2     3     4    64 12345    64     8     9]
[   64 12345    64]


In [124]:

arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [127]:
arr[5:8].copy()
# hum esy copy b krskty hn

array([64, 64, 64])

In [134]:
arr2d = np.array([[1, 2, -3], [4, 5, 6], [7, 8, 9]])


In [161]:
arr3d[0] = old_values
arr3d


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [171]:
a = arr3d[0].copy()
arr3d[0] = 45
arr3d

array([[[45, 45, 45],
        [45, 45, 45]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [172]:
arr3d[0] = a 
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [173]:
#Similarly, arr3d[1, 0] gives you all of the values whose indices start with (1, 0),
#forming a 1-dimensional array:
arr3d[1, 0]

array([7, 8, 9])

In [177]:
#This expression is the same as though we had indexed in two steps:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [178]:
x[0]

array([7, 8, 9])

In [180]:
arr #indexing with slicing

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [181]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [183]:
#Consider the two-dimensional array from before, arr2d. Slicing this array is a bit
#different:
arr2d

array([[ 1,  2, -3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [185]:
arr2d[:2]

array([[ 1,  2, -3],
       [ 4,  5,  6]])

In [186]:
#You can pass multiple slices just like you can pass multiple indexes
arr2d[:2, 1:]

array([[ 2, -3],
       [ 5,  6]])

In [187]:
# For example, I can select the second row but only the first two columns like so:
arr2d[1, :2]

array([4, 5])

In [188]:
#Similarly, I can select the third column but only the first two rows like so:
arr2d[:2, 2]

array([-3,  6])

In [189]:
#See Figure 4-2 for an illustration. Note that a colon by itself means to take the entire
#axis, so you can slice only higher dimensional axes by doing:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [190]:
# Of course, assigning to a slice expression assigns to the whole selection:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [2]:
import numpy as np

In [8]:
x=np.zeros ((4,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones ((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
b = np.empty((8,8))
b

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [23]:
a.dtype

dtype('float64')

In [24]:
# or 
type(a[0])

numpy.float64

In [25]:
b = np.ones(6)
b

array([1., 1., 1., 1., 1., 1.])

In [26]:
b.dtype

dtype('float64')

In [27]:
type(b[0])

numpy.float64

In [33]:
c = np.empty(10)
c

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
c.dtype

dtype('float64')

In [35]:
c.shape

(10,)

In [36]:
c.shape = (5,2)
c

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [39]:
d= np.linspace(3,20,5)   # is ne 3 se 20 tak aik array banay jis mek hi simmilar gap ho go 
d

array([ 3.  ,  7.25, 11.5 , 15.75, 20.  ])

In [44]:
d = np.linspace(5,100,5)
d

array([  5.  ,  28.75,  52.5 ,  76.25, 100.  ])

In [45]:
e = np.arange(3,100,5)
e

array([ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58, 63, 68, 73, 78, 83,
       88, 93, 98])

In [46]:
list = [5,4,2,6,8,2,3,1]     # ye aik liat h 
list

[5, 4, 2, 6, 8, 2, 3, 1]

In [47]:
g = np.array(list)   # hum ne aik list ok array bana dia
g

array([5, 4, 2, 6, 8, 2, 3, 1])

In [48]:
g.shape

(8,)

In [51]:
x = np.random.randint(10,size = (2,5))
x




array([[9, 0, 3, 3, 0],
       [3, 7, 3, 6, 4]])

In [53]:
x = np.random.randint(10,size = 10)
x




array([4, 9, 4, 4, 0, 0, 6, 8, 2, 4])

In [54]:
x = np.random.randint(10)
x




2

In [59]:
x = np.random.randint(10,size = 100)
x




array([8, 9, 7, 4, 6, 9, 1, 5, 8, 4, 4, 4, 4, 4, 5, 4, 4, 7, 5, 3, 8, 1,
       0, 8, 6, 5, 7, 1, 8, 9, 8, 9, 4, 0, 0, 4, 2, 5, 6, 9, 2, 7, 7, 8,
       9, 2, 0, 5, 2, 0, 3, 0, 8, 0, 6, 1, 9, 9, 4, 2, 5, 8, 1, 1, 7, 6,
       7, 3, 2, 1, 3, 3, 1, 8, 6, 0, 2, 4, 3, 3, 9, 7, 7, 1, 6, 9, 4, 0,
       5, 4, 2, 0, 7, 3, 0, 7, 8, 4, 7, 4])

In [60]:
y = np.random.randint(55)
y




37

In [61]:
x[0]

8

In [62]:
x[5:10]

array([9, 1, 5, 8, 4])

In [63]:
x[-1]

4

In [68]:
x >2

array([ True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False, False,  True,
       False,  True,  True,  True, False,  True,  True,  True,  True,
       False, False,  True, False, False,  True, False,  True, False,
        True, False,  True,  True,  True, False,  True,  True, False,
       False,  True,  True,  True,  True, False, False,  True,  True,
       False,  True,  True, False, False,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True, False,  True,  True,
       False, False,  True,  True, False,  True,  True,  True,  True,
        True])

In [69]:
x[x> 4]

array([8, 9, 7, 6, 9, 5, 8, 5, 7, 5, 8, 8, 6, 5, 7, 8, 9, 8, 9, 5, 6, 9,
       7, 7, 8, 9, 5, 8, 6, 9, 9, 5, 8, 7, 6, 7, 8, 6, 9, 7, 7, 6, 9, 5,
       7, 7, 8, 7])

In [70]:
x[x< 4]

array([1, 3, 1, 0, 1, 0, 0, 2, 2, 2, 0, 2, 0, 3, 0, 0, 1, 2, 1, 1, 3, 2,
       1, 3, 3, 1, 0, 2, 3, 3, 1, 0, 2, 0, 3, 0])

In [71]:
x@x

2923

In [13]:
l = [1,3,5,7,9]

In [16]:
np.array(l)

array([1, 3, 5, 7, 9])

In [17]:
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [44]:
x=np.arange(1,200,15)
x

array([  1,  16,  31,  46,  61,  76,  91, 106, 121, 136, 151, 166, 181,
       196])

In [45]:
x.shape

(14,)

In [46]:
x = np.zeros ((10,10))

In [47]:
x.shape

(10, 10)

In [48]:
y = x.reshape((2,2,5,5))

In [49]:
y

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [50]:
y.dtype

dtype('float64')

In [51]:
y.ndim

4

In [53]:
import numpy as np

In [56]:
a=np.random.randn((10))

In [57]:
b=np.random.randn((10))

In [58]:
a

array([ 0.01842428, -0.426487  , -0.15379844, -0.63389808, -0.14813651,
        0.5608386 ,  0.29432295,  0.6719944 , -1.54141773,  0.14878911])

In [59]:
b

array([-0.35038309,  0.61631748,  0.64286399,  0.19882669, -0.40917722,
       -0.03018038,  0.37862828,  0.34361034, -0.13637501, -0.96883403])

In [60]:
a+b

array([-0.33195881,  0.18983048,  0.48906555, -0.43507138, -0.55731373,
        0.53065823,  0.67295123,  1.01560475, -1.67779274, -0.82004492])

In [61]:
a-b

array([ 0.36880737, -1.04280448, -0.79666243, -0.83272477,  0.26104071,
        0.59101898, -0.08430534,  0.32838406, -1.40504272,  1.11762314])

In [62]:
2*a

array([ 0.03684856, -0.85297399, -0.30759687, -1.26779615, -0.29627302,
        1.12167721,  0.5886459 ,  1.3439888 , -3.08283547,  0.29757823])

In [63]:
1/a

array([54.27620763, -2.34473738, -6.50201664, -1.57754068, -6.75053035,
        1.78304417,  3.39762838,  1.48810764, -0.6487534 ,  6.72092186])

In [64]:
a>0

array([ True, False, False, False, False,  True,  True,  True, False,
        True])

In [65]:
2*b

array([-0.70076617,  1.23263496,  1.28572798,  0.39765339, -0.81835444,
       -0.06036075,  0.75725657,  0.68722069, -0.27275002, -1.93766806])

In [2]:
import numpy as np

In [4]:
a= np.array([1,3,11,5,9,7,])    ye array me list h
print(a)

[ 1  3 11  5  9  7]


In [11]:
print(a[4]) # vLUE 5 m kia dekha hum ne

9


In [12]:
print(a[a>5])    # boolean indexing jo value 5 se bari h vo true value samny a gai 

[11  9  7  8]


In [13]:
a[[2,1]]    # fancy indenxing yani agr kisi array ko koi list pass on kr dain jis m hum specify value ki indexing
              # kre k specify element pick kr lie

array([11,  3])

In [16]:
x= np.random.randn(10,10)     #slicing
print(x)

[[-0.78067296 -0.08592697 -0.19553143 -0.29446106 -0.33961727 -0.72761597
  -0.48502207  1.56695826 -1.31794975 -0.3274491 ]
 [ 0.09790805 -0.26229501  0.56047912  0.57939712 -1.34149396 -0.63950626
   1.47753843 -0.89928436 -0.03096146 -0.33491637]
 [-0.33130322  0.46810883  1.15736764  0.8910997  -1.19996606 -0.5948201
  -0.21536647 -0.22769337 -0.21383488 -1.01395529]
 [-1.24118135 -0.67651785 -0.54242987  1.49612163 -0.93852408  0.87873328
  -0.81332413 -1.06031016 -0.96082482 -0.35513758]
 [-0.22344818  0.73179201 -1.37773544  0.23507241  0.90040905  1.35484379
  -0.27428357 -0.22377106 -0.62257912 -0.64543996]
 [-0.03440405  0.2293468  -0.74139855 -1.96854874 -0.59509269  1.83570736
   1.77002507  1.66310952  0.52655357  0.21887339]
 [ 1.28222354 -0.11354007  1.43708024  0.51397228 -1.16103261  0.52597174
   1.35114425 -0.22225185  1.46376301  1.57814684]
 [ 0.57582169 -0.26795582  1.18744393 -0.73291252  0.87264308  1.22306291
  -0.99728726 -0.80733893 -1.00133426  0.51961132]
 

In [17]:
x[0]     # to  pick 1 row

array([-0.78067296, -0.08592697, -0.19553143, -0.29446106, -0.33961727,
       -0.72761597, -0.48502207,  1.56695826, -1.31794975, -0.3274491 ])

In [18]:
x[0][4]  # agr first row se fifth collum pick krna ho to 

-0.3396172737981365

In [19]:
x[0][5]

-0.7276159692107567

In [20]:
x[1:10:2]

array([[ 0.09790805, -0.26229501,  0.56047912,  0.57939712, -1.34149396,
        -0.63950626,  1.47753843, -0.89928436, -0.03096146, -0.33491637],
       [-1.24118135, -0.67651785, -0.54242987,  1.49612163, -0.93852408,
         0.87873328, -0.81332413, -1.06031016, -0.96082482, -0.35513758],
       [-0.03440405,  0.2293468 , -0.74139855, -1.96854874, -0.59509269,
         1.83570736,  1.77002507,  1.66310952,  0.52655357,  0.21887339],
       [ 0.57582169, -0.26795582,  1.18744393, -0.73291252,  0.87264308,
         1.22306291, -0.99728726, -0.80733893, -1.00133426,  0.51961132],
       [-0.44380311,  0.54895941,  2.85454251, -1.36467134,  0.23839378,
         0.16977282, -1.74881819,  0.57481538, -0.95548143,  1.36042776]])

In [21]:
x[1:10:2,::]    # all odd rows (,::)

array([[ 0.09790805, -0.26229501,  0.56047912,  0.57939712, -1.34149396,
        -0.63950626,  1.47753843, -0.89928436, -0.03096146, -0.33491637],
       [-1.24118135, -0.67651785, -0.54242987,  1.49612163, -0.93852408,
         0.87873328, -0.81332413, -1.06031016, -0.96082482, -0.35513758],
       [-0.03440405,  0.2293468 , -0.74139855, -1.96854874, -0.59509269,
         1.83570736,  1.77002507,  1.66310952,  0.52655357,  0.21887339],
       [ 0.57582169, -0.26795582,  1.18744393, -0.73291252,  0.87264308,
         1.22306291, -0.99728726, -0.80733893, -1.00133426,  0.51961132],
       [-0.44380311,  0.54895941,  2.85454251, -1.36467134,  0.23839378,
         0.16977282, -1.74881819,  0.57481538, -0.95548143,  1.36042776]])

In [22]:
x[::,0:4]   # ALL odd ROW aur 4 colum

array([[-0.78067296, -0.08592697, -0.19553143, -0.29446106],
       [ 0.09790805, -0.26229501,  0.56047912,  0.57939712],
       [-0.33130322,  0.46810883,  1.15736764,  0.8910997 ],
       [-1.24118135, -0.67651785, -0.54242987,  1.49612163],
       [-0.22344818,  0.73179201, -1.37773544,  0.23507241],
       [-0.03440405,  0.2293468 , -0.74139855, -1.96854874],
       [ 1.28222354, -0.11354007,  1.43708024,  0.51397228],
       [ 0.57582169, -0.26795582,  1.18744393, -0.73291252],
       [ 0.06302977, -0.70133269, -1.43920236, -1.95000648],
       [-0.44380311,  0.54895941,  2.85454251, -1.36467134]])

In [29]:
x=np.ones((5,5))        # square shape jis k board pr one aur innerlly 0 ho
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [31]:
x[1:-1,1:-1]=0      # first and last row skip ki
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Topic 6

Fast element wise array Functions

In [1]:
import numpy as np

In [2]:
x = np.array([10,9,8,6,11])
x

array([10,  9,  8,  6, 11])

In [3]:
np.sqrt(x)

array([3.16227766, 3.        , 2.82842712, 2.44948974, 3.31662479])

In [4]:
np.power(x,2)  # everu element ka square nikal skty hain

array([100,  81,  64,  36, 121], dtype=int32)

In [5]:
y= np.array([7,1,2,3,-1])
y

array([ 7,  1,  2,  3, -1])

In [6]:
np.maximum(x,y)  # element wise maximum number

array([10,  9,  8,  6, 11])

# Topic 7
np.where()

In [ ]:
A vectorized version of the ternary 

In [ ]:
x if condition else y

condition? Expression1: Expression2
    
    

# Ternary Operator
ye esa operator h jo three operation perform deta h 
first = condition, 2nd Expr1 =  true, 3rd expr2 = False

In [ ]:
# Example
x > 10 = "Hellow",True    ye Ternary operator h
x< 10= "World", False

In [ ]:
np.where(condition),(option A), (option B)

Condition     =  the condition 
Option A     =  what to do with entries which the condition it True
Option B     =  what to do with entires which the condition it False
    
    
ye condition all array pr apply ho gi 
jb data scince m work krty hain to bazdafa humary pass esa data ata h jis m kuch field missing ho
ti hain in missing value k liye hum where ka function use krty hain 



In [2]:
import numpy as np
salary = np.array ([0,-1,100000,500000])
salary

array([     0,     -1, 100000, 500000])

In [5]:
np.where(salary <= 0,25000,salary)

array([ 25000,  25000, 100000, 500000])

In [6]:
# or 
np.where(salary <=0, "Not Ok", "Ok")

array(['Not Ok', 'Not Ok', 'Ok', 'Ok'], dtype='<U6')

In [91]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8])
b = np.array([8,7,1,3,9,8,3,7])
a,b

(array([1, 2, 3, 4, 5, 6, 7, 8]), array([8, 7, 1, 3, 9, 8, 3, 7]))

In [92]:
np.where(a>b, a,b)

array([8, 7, 3, 4, 9, 8, 7, 8])

In [93]:
result = np.array([30,40,50,63,25,90,73])

In [94]:
np.where(result>40,"Pass","Fail")

array(['Fail', 'Fail', 'Pass', 'Pass', 'Fail', 'Pass', 'Pass'],
      dtype='<U4')

# Topic 8v
Mathhematical & Statistical Methods

In [ ]:
mean(): returns the mean value computed over the array
    
cumsum(): returns the cumulative sum of array element
    
cumpord(): returns the cumulative product of array     

# example
Boolean Array 

Sum()
hum dekhna chaa rhe heain k kitny element True hain is k liye use ho ga function 
sum(): counting True values in a boolean array (sum = Count & True = 1) hum boolean array me dekhy gy 


In [ ]:
any():  test whether one more value an array is True (ek ya ek se ziada value true hon gyi)

In [ ]:
all(): check if every value is True (agr all value true ni hain to False show ho ga)

In [ ]:
unique(): is se hum unique element dhekh skty hain 

In [ ]:
np.sort(): the sorts the value of a numpy 

In [28]:
x = np.array([10,9,7,10,7])
x

array([10,  9,  7, 10,  7])

In [9]:
x.mean()   #avarage of all array 

8.6

In [10]:
x.cumsum()   # every element of array add(+)  to next element 

array([10, 19, 26, 36, 43], dtype=int32)

In [12]:
x.cumprod()

array([   10,    90,   630,  6300, 44100], dtype=int32)

In [14]:
y = x> 6 
y

array([ True,  True,  True,  True,  True])

In [15]:
y.sum()

5

In [16]:
y.any()

True

In [18]:
y.all()

True

In [20]:
y = x> 7
y

array([ True,  True, False,  True, False])

In [21]:
y.sum()

3

In [22]:
y.any()

True

In [23]:
y.all()

False

In [25]:
y.sort()
y

array([False, False,  True,  True,  True])

In [29]:
x.sort()
x

array([ 7,  7,  9, 10, 10])

In [95]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [96]:
a.mean()

5.5

In [97]:
a.sum()

66

In [98]:
a.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66], dtype=int32)

In [99]:
a.cumprod()  # agar ek b value zero ho gi to sari value zero ho jai gi 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [100]:
b = np.arange(1,10)
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
b.cumprod()

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880], dtype=int32)

In [105]:
b.prod()

362880

In [106]:
a.prod()

0

In [108]:
np.unique(a)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [115]:
b = np.array([0,1,2,3,4,5,6,7,8,9])
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
c = b>5
c

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [117]:
b.sum()

45

In [118]:
c.sum()

4

In [119]:
b.any()

True

In [120]:
b.all()

False

In [122]:
arr = np.array([1,2,5,5,4,2,1,6,6,5,1,])
arr

array([1, 2, 5, 5, 4, 2, 1, 6, 6, 5, 1])

In [123]:
np.unique(arr)     #ye np ka function h is liye is k sth np. lagay agia h baqi funs python 
                    #  m b hain

array([1, 2, 4, 5, 6])

In [126]:
arr.sort()
arr

array([1, 1, 1, 2, 2, 4, 5, 5, 5, 6, 6])

# Topic 9

File input output

In [ ]:
np.save(filename.npy,array)   # single file m hum agar extesion ni be btay to numpy khud hi bta
                                # de ga 

In [ ]:
np.load(filename.npy)

In [ ]:
np.saves(filename.npz,arra1,arry2)  # for more files yaha extension btana zarury h   

In [ ]:
np.load(filesname.npz,array1,array2)  # when loading.npz file, you get back a 
                                         # dictionary like object

In [2]:
import numpy as np
x = [1,4,5,6]
y = [8,4,9]

In [3]:
x

[1, 4, 5, 6]

In [4]:
y

[8, 4, 9]

In [5]:
np.save("testx.npy",x)   # save krty waqat extension likhna zaruri ni

In [6]:
loadx = np.load("testx.npy")    # load krty waqt extention likhna zaruri h 
loadx


array([1, 4, 5, 6])

In [7]:
np.savez("testxy.npz",x=x,y=y)   #yahan (=)sign lagana bht zaruri h agr (=) in likhy gay to 
                                   # files save ni hon gi  

In [8]:
loadxy = np.load("testxy.npz")

In [9]:
loadxy                      # ye ek dicyionary h

In [10]:
loadxy['x'] 

array([1, 4, 5, 6])

In [11]:
loadxy['y']

array([8, 4, 9])

In [12]:
name1 = ["Ahamd", " Muneeb", "Umar","Jarar Haider"]
name2 = ["Nazia Sajjad", "Noreen Nasir", "Naeem Jaffar", "Imran Jafar", "Saba", "Sulaman Jaffar"]

In [13]:
name1

['Ahamd', ' Muneeb', 'Umar', 'Jarar Haider']

In [14]:
name2

['Nazia Sajjad',
 'Noreen Nasir',
 'Naeem Jaffar',
 'Imran Jafar',
 'Saba',
 'Sulaman Jaffar']

In [16]:
np.save("kids",name1)   # extension likhna zaruri ni

In [21]:
l1 = np.load("kids.npy") # load krwaty waqt extension likhna zaruri h (npy) single 
                                 #file k liye

In [22]:
l1

array(['Ahamd', ' Muneeb', 'Umar', 'Jarar Haider'], dtype='<U12')

In [29]:
np.savez("adults", name1 = name1, name2 = name2)  # extension likhna zaruri ni

In [30]:
l2 = np.load("adults.npz")  # load krwaty waqt extension likhna zaruri h (npz) single 
                                 #file k liye

In [33]:
l2          # numpy is ko dictionary consider kry ga 

In [35]:
l2["name1"]   # [name1] = key of dictionary 

array(['Ahamd', ' Muneeb', 'Umar', 'Jarar Haider'], dtype='<U12')

In [36]:
l2["name2"]

array(['Nazia Sajjad', 'Noreen Nasir', 'Naeem Jaffar', 'Imran Jafar',
       'Saba', 'Sulaman Jaffar'], dtype='<U14')

# Topic 10
Linear Algebra Functions 

In [71]:
x = np.random.randn(3,2)
x

array([[-0.28364364,  0.44196583],
       [-0.0627798 , -0.91896481],
       [ 1.19279956, -0.2405539 ]])

In [72]:
y = np.random.randn(2,3)
y

array([[-0.13579738, -0.4725718 , -0.50944264],
       [-0.96115272, -1.13325898, -0.63020668]])

In [73]:
x.dot(y)

array([[-0.38627859, -0.36681976, -0.13402965],
       [ 0.89179086,  1.07109309,  0.61112047],
       [ 0.06922998, -0.29107356, -0.45606428]])

In [74]:
x.transpose()

array([[-0.28364364, -0.0627798 ,  1.19279956],
       [ 0.44196583, -0.91896481, -0.2405539 ]])

In [76]:
y.transpose()

array([[-0.13579738, -0.96115272],
       [-0.4725718 , -1.13325898],
       [-0.50944264, -0.63020668]])

In [80]:
y.trace()

-1.269056362834895

In [82]:
x.trace()

-1.2026084569832776

# how to compute dot product of two vactors?

In [43]:
a= np.array([ 1,3,5,9])
b = np.array([3,5,9,8])

In [44]:
np.dot(a,b)

135

In [45]:
np.dot(b,a)

135

# How to compute dot product of two matrix and vactor?

In [46]:
x = np.array([[5,8,9,6],[7,2,3,8]])
x

array([[5, 8, 9, 6],
       [7, 2, 3, 8]])

In [48]:
np.dot(x,a)  # yaha matrix x, aur vactor a ka dot product liya gia ha 

array([128, 100])

In [51]:
np.dot(x,b)

array([184, 122])

# How to compute transpose of a matrix?

In [52]:
x = np.array([[5,8,9,6],[7,2,3,8]])
x

array([[5, 8, 9, 6],
       [7, 2, 3, 8]])

In [53]:
np.transpose(x)   #row column & column row bn jaty hain 

array([[5, 7],
       [8, 2],
       [9, 3],
       [6, 8]])

# how to create identity matrix?

In [55]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [59]:
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [58]:
np.identity(3,4)

TypeError: data type not understood

# how to compute inverse of a matrix?

In [61]:
c = np.array([[1.,2.,3.],[10.,5.,6.],[7.,8.,9.]])
c

array([[ 1.,  2.,  3.],
       [10.,  5.,  6.],
       [ 7.,  8.,  9.]])

In [63]:
c_inv = np.linalg.inv(c)
c_inv

array([[-0.08333333,  0.16666667, -0.08333333],
       [-1.33333333, -0.33333333,  0.66666667],
       [ 1.25      ,  0.16666667, -0.41666667]])

# How to perform Matrix Multiplication?

In [64]:
np.dot(c,c_inv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [65]:
# or 
c@c_inv

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# How to compute trace of a matrix?

In [66]:
y = np.array([[1,2,3],[4,5,6]])
y

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
np.trace(y)

6

# how to compute determinant of a matrix?

In [71]:
a = np.array([[4.,6.],[3,7]])
a

array([[4., 6.],
       [3., 7.]])

In [72]:
np.linalg.det(a)

10.000000000000002

In [78]:
b = np.array([[3.,4.],[6,8]])
b

array([[3., 4.],
       [6., 8.]])

In [79]:
np.linalg.det(b)

0.0

# Topic 11
Pseudo random number generator

# Pseudo random number generator


                                 Transformation Function
                                     
                                     
Seed = (intialization function)     = Start=   (output Function) = Random bits
                        
                                      PRNG



# distribution


np.normal()
np.seed()
np.uniform()
np.gama()

Note: distribution is k ilawa bi hain jo book m hain 

In [68]:
np.random.seed(7)  # hum ko kuch performice nazar ni aye gi magar machine samage jay gi 

In [55]:
a = np.random.random((3,3))
a

array([[0.23743592, 0.94056563, 0.82065819],
       [0.05175957, 0.00185465, 0.17697245],
       [0.53842584, 0.53801619, 0.51176963]])

In [44]:
a = np.random.rand(3,3)
a

array([[0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286],
       [0.20484909, 0.49076589, 0.37238469]])

In [45]:
np.random.randint(10,size = 10)

array([7, 7, 9, 3, 0, 7, 7, 7, 0, 5])

In [46]:
np.random.randint(100,size = 10)

array([35, 97, 67, 91, 97, 19, 27,  4, 19, 33])

In [48]:
np.random.randint(100,size = (10,10))      # 2 d array 

array([[30, 57, 73, 93, 81, 31,  2, 83, 50, 18],
       [21, 67, 75, 58, 47, 16, 12, 93,  9, 76],
       [67, 14, 20, 53, 15, 59, 35, 48,  4, 43],
       [72, 90, 54, 43, 87, 77, 50, 39,  3, 29],
       [12, 76, 79, 29,  8, 54, 38, 70, 21, 44],
       [91,  7, 81, 69, 52, 41, 29, 26, 64, 62],
       [86, 98, 12,  6, 34, 59, 93, 17,  5, 79],
       [49, 54, 76, 92, 54, 47, 37, 73, 87, 21],
       [ 4, 91, 76, 75,  6, 97, 85, 85, 30, 92],
       [56, 51, 55, 12, 76, 36, 71, 85, 58, 41]])

In [51]:
np.random.randint(50,size = (3,10,2))  # 3 dimension array

array([[[41, 11],
        [42, 32],
        [40, 36],
        [ 5, 28],
        [43, 29],
        [49, 46],
        [42, 48],
        [31,  7],
        [28, 47],
        [48, 14]],

       [[47, 13],
        [19, 41],
        [13, 24],
        [ 3,  7],
        [49, 42],
        [32, 33],
        [11, 27],
        [ 4, 38],
        [31, 49],
        [30, 14]],

       [[44, 43],
        [12, 16],
        [49, 26],
        [32, 43],
        [33,  8],
        [30, 33],
        [15, 22],
        [34, 12],
        [ 4, 44],
        [20, 43]]])

In [32]:
np.random.normal(size = (3,3))

array([[ 1.69052570e+00, -4.65937371e-01,  3.28201637e-02],
       [ 4.07516283e-01, -7.88923029e-01,  2.06557291e-03],
       [-8.90385858e-04, -1.75472431e+00,  1.01765801e+00]])

In [56]:
np.random.normal(9,size = (3,3))   # 2 d array

array([[ 9.60049852,  8.65670501, 10.64678145],
       [ 8.71414156,  9.94754803,  9.67354274],
       [ 7.53647128,  8.61813623,  8.54053598]])

In [58]:
np.random.normal(10,size = (5))   # 1 d array

array([10.49153177,  9.50094978,  9.46339152, 11.91206737, 11.59971117])

In [63]:
np.random.gamma(3,size =10)

array([1.2527844 , 4.37254301, 1.52790833, 6.06843435, 2.65268882,
       0.5648966 , 2.34715587, 1.60594162, 3.3033944 , 1.36947676])

In [64]:
np.random.gamma(10,size =3)

array([ 7.04034609, 10.98516931,  5.08834542])

In [66]:
np.random.gamma(10,5)

48.96572908030073

In [71]:
np.random.uniform(10,size = (2,5))


array([[9.3132254 , 2.98073087, 6.05431692, 3.4888134 , 1.19809439],
       [5.15353717, 5.48991583, 9.3515398 , 7.58404918, 5.50105749]])

# Topic 12
Numpy advanced array Manipulation
hum agly tamam lecture Advanced array manipulation k dekhy gy 


# Topic 13
Reshape 

In [73]:
a = np.array([0,1,2,3,4,5,6,7,8,9,10,11]).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
c order (row major) C order    by defualt row order hota hai
Fortran order (column major)  F order

# Reshpae arrays
1 ------ C Order : Row major order  (C language)
2 ------- Fortran Order:  Column major oder
3 ------ Specifying: for reshape() means the value used for that dimension will be inferred from
            the data.
4 -------- ravel() or fltten()  for flattening to one dimension. 

In [81]:
x = np.random.randn(4,5)

x

array([[-0.7528372 , -1.7083392 , -1.80309866,  0.38312185,  2.24759505],
       [ 0.26941163, -0.52460462,  1.91201886,  0.23730185,  0.10143399],
       [ 0.25257774, -0.1323772 , -0.30947634, -1.43496347,  0.50162412],
       [-0.09477545,  1.19308592, -0.36881847, -1.90636988, -0.09961063]])

In [82]:
x.reshape(2,2,5)  # column order = "F"

array([[[-0.7528372 , -1.7083392 , -1.80309866,  0.38312185,
          2.24759505],
        [ 0.26941163, -0.52460462,  1.91201886,  0.23730185,
          0.10143399]],

       [[ 0.25257774, -0.1323772 , -0.30947634, -1.43496347,
          0.50162412],
        [-0.09477545,  1.19308592, -0.36881847, -1.90636988,
         -0.09961063]]])

In [83]:
x.reshape(2,2,-1)  #hum kisi dimension ko skip bi kr skty hain 

array([[[-0.7528372 , -1.7083392 , -1.80309866,  0.38312185,
          2.24759505],
        [ 0.26941163, -0.52460462,  1.91201886,  0.23730185,
          0.10143399]],

       [[ 0.25257774, -0.1323772 , -0.30947634, -1.43496347,
          0.50162412],
        [-0.09477545,  1.19308592, -0.36881847, -1.90636988,
         -0.09961063]]])

In [84]:
x

array([[-0.7528372 , -1.7083392 , -1.80309866,  0.38312185,  2.24759505],
       [ 0.26941163, -0.52460462,  1.91201886,  0.23730185,  0.10143399],
       [ 0.25257774, -0.1323772 , -0.30947634, -1.43496347,  0.50162412],
       [-0.09477545,  1.19308592, -0.36881847, -1.90636988, -0.09961063]])

In [85]:
x.ravel()

array([-0.7528372 , -1.7083392 , -1.80309866,  0.38312185,  2.24759505,
        0.26941163, -0.52460462,  1.91201886,  0.23730185,  0.10143399,
        0.25257774, -0.1323772 , -0.30947634, -1.43496347,  0.50162412,
       -0.09477545,  1.19308592, -0.36881847, -1.90636988, -0.09961063])

In [87]:
# or 
x.flatten()       #is se hum high dimension array ko 1 d array bna skty hain 

array([-0.7528372 , -1.7083392 , -1.80309866,  0.38312185,  2.24759505,
        0.26941163, -0.52460462,  1.91201886,  0.23730185,  0.10143399,
        0.25257774, -0.1323772 , -0.30947634, -1.43496347,  0.50162412,
       -0.09477545,  1.19308592, -0.36881847, -1.90636988, -0.09961063])

In [2]:
import numpy as np
a= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [4]:
a.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
#OR 
a.reshape(3,4, order = "c")

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
a.reshape(3,4, order = "f")    # column wise counting hoi h 

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [9]:
a.reshape(3,2,2, order = "c")

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [10]:
a.reshape(2,3,2, order = "f")

array([[[ 1,  7],
        [ 3,  9],
        [ 5, 11]],

       [[ 2,  8],
        [ 4, 10],
        [ 6, 12]]])

In [12]:
b = a.reshape(2,3,2, order = "f")
b

array([[[ 1,  7],
        [ 3,  9],
        [ 5, 11]],

       [[ 2,  8],
        [ 4, 10],
        [ 6, 12]]])

In [13]:
c = a.reshape(2,3,2, order = "c")
c

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [14]:
c.ravel()    # row wise ravel hwa h 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [15]:
b.ravel()   # column wise ravel howa h

array([ 1,  7,  3,  9,  5, 11,  2,  8,  4, 10,  6, 12])

In [17]:
# or
b.flatten()     # column wise ravel howa h

array([ 1,  7,  3,  9,  5, 11,  2,  8,  4, 10,  6, 12])

In [18]:
 # or
c.flatten()      # row wise ravel howa h

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# topic 14

Numpy Concatenate 

In [ ]:
Takes a sequence (tuple, list, etc) of arrays & joins them togather in order along them 
input axis 

In [ ]:
example  
setting axis = 0 Concatenate along the  row axis


In [11]:
import numpy as np
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
b = np.array([9.,9.,9.,9.,9.,9.]).reshape(2,3)
b

array([[9., 9., 9.],
       [9., 9., 9.]])

In [13]:
np.concatenate((a,b), axis = 0) # vertical (row wise Concatenate)

array([[1., 1., 1.],
       [1., 1., 1.],
       [9., 9., 9.],
       [9., 9., 9.]])

In [14]:
import numpy as np
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
b = np.array([9.,9.,9.,9.,9.,9.]).reshape(2,3)
b

array([[9., 9., 9.],
       [9., 9., 9.]])

In [16]:
np.concatenate((a,b), axis = 1) # horizontal (column wise Concatenate)

array([[1., 1., 1., 9., 9., 9.],
       [1., 1., 1., 9., 9., 9.]])

# convenience function
1 Vstack: arrays row wise along axis = 0
2 hstack : arrays column wise along axis = 1

In [17]:
x = [[1,3,5],[7,9,0]]

In [18]:
arr1 = np.array(x)

In [25]:
arr1

array([[1, 3, 5],
       [7, 9, 0]])

In [20]:
y = [[11,15,18],[17,18,10]]

In [21]:
arr2 = np.array(y)

In [24]:
arr2

array([[11, 15, 18],
       [17, 18, 10]])

In [28]:
np.concatenate((arr1,arr2), axis = 0)

array([[ 1,  3,  5],
       [ 7,  9,  0],
       [11, 15, 18],
       [17, 18, 10]])

In [29]:
# or
np.vstack((arr1,arr2))

array([[ 1,  3,  5],
       [ 7,  9,  0],
       [11, 15, 18],
       [17, 18, 10]])

In [32]:
np.concatenate((arr1,arr2), axis = 0)

array([[ 1,  3,  5],
       [ 7,  9,  0],
       [11, 15, 18],
       [17, 18, 10]])

In [33]:
np.hstack((arr1,arr2))

array([[ 1,  3,  5, 11, 15, 18],
       [ 7,  9,  0, 17, 18, 10]])

In [34]:
#or
np.concatenate((arr1,arr2), axis = 1)

array([[ 1,  3,  5, 11, 15, 18],
       [ 7,  9,  0, 17, 18, 10]])

# Topic 15

split : matlb torna 

split slices apart an array into multiple array along an axis

In [35]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.split(arr1,[2,6])    # position 2 se spilt , position 6 se split howa

[array([1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [38]:
x = [1,4,5,6,7,9,1,4]

In [39]:
d = np.array(x)

In [40]:
d

array([1, 4, 5, 6, 7, 9, 1, 4])

In [41]:
np.split(d,[3,5])

[array([1, 4, 5]), array([6, 7]), array([9, 1, 4])]

In [53]:
y = [[1,4,5,6,9,1,4],[4,11,18,15,19,21,11]]

In [54]:
d2 = np.array(y)

In [55]:
d2

array([[ 1,  4,  5,  6,  9,  1,  4],
       [ 4, 11, 18, 15, 19, 21, 11]])

In [56]:
np.split(d2,[3,5], axis = 1)

[array([[ 1,  4,  5],
        [ 4, 11, 18]]),
 array([[ 6,  9],
        [15, 19]]),
 array([[ 1,  4],
        [21, 11]])]

In [58]:
np.split(d2,[4,6],axis = 0)

[array([[ 1,  4,  5,  6,  9,  1,  4],
        [ 4, 11, 18, 15, 19, 21, 11]]),
 array([], shape=(0, 7), dtype=int32),
 array([], shape=(0, 7), dtype=int32)]

In [60]:
np.split(d2,[1],axis = 1)

[array([[1],
        [4]]),
 array([[ 4,  5,  6,  9,  1,  4],
        [11, 18, 15, 19, 21, 11]])]

In [63]:
np.split(d2,[1],axis = 0)

[array([[1, 4, 5, 6, 9, 1, 4]]), array([[ 4, 11, 18, 15, 19, 21, 11]])]

# topic 16

tile & Repeat

In [ ]:
Repeat()

1 repeat replicates each element in an array some number of times producting a large array
2 if you pass an array of integers each element can be repeated a different number of times

In [ ]:
example

np.repeat()
repeats every item of an input, and puts the repeated numbers into a nw array

In [64]:
x = np.array([6,7,8])
x

array([6, 7, 8])

In [65]:
np.repeat(x,3)

array([6, 6, 6, 7, 7, 7, 8, 8, 8])

In [66]:
np.repeat(x,2)   

array([6, 6, 7, 7, 8, 8])

# Tile()

In [ ]:
tile is a shortcut for stacking copies of an array along an axis 

In [72]:
y = np.arange(4).reshape(2,2)
y

array([[0, 1],
       [2, 3]])

In [73]:
np.tile(y,2)

array([[0, 1, 0, 1],
       [2, 3, 2, 3]])

In [90]:
np.tile(y,4)

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [2, 3, 2, 3, 2, 3, 2, 3]])

In [109]:
#task12
def function12():
    # Create the following pattern without hardcoding. Use only numpy functions and the below input array arr.
    # HINT: use stacking concept
    
    arr = np.array([1,2,3])
    ans = np.hstack((np.repeat(arr,3),arr,arr,arr)) #write your code here 
  
    return ans

    """
     Expected Output:
              array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
     """ 

function12()

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])