In [ ]:
def square(values):
    result=[]
    for v in values:
        result.append(v * 2)
    return result

In [ ]:
to_square = range (100000)

In [ ]:
%timeit square(to_square)

In [3]:
import numpy as np

In [4]:
array_to_square = np.arange(0,100000)

In [5]:
%timeit array_to_square ** 2    # micro second mai answer aya h numpy 1000 time fast h python seS

145 µs ± 16.2 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [7]:
#create numpy array , performing basic array operations

In [8]:
# python list method  1
arr = np.array([11,22,33,44,55])
arr

array([11, 22, 33, 44, 55])

In [11]:
type(arr)

numpy.ndarray

In [12]:
np.size(arr)

5

In [13]:
arr.dtype


dtype('int32')

In [40]:
testarr = np.array([1,2,3.0,4,5])

testarr

array([1., 2., 3., 4., 5.])

In [41]:
arr2 = np.array([1,2,6,8,3]) # 1 dimension array ko vector b kehty hn. 2 dimension array ko 
                               #matrix kehty hn

arr2

array([1, 2, 6, 8, 3])

In [42]:
np.shape(arr2)

(5,)

In [43]:
#method 2 
#creat array 
np.array(range(20))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [48]:
# Method
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [49]:
arr3 = np.arange(20,50)
arr3

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [50]:
arr = np.arange(0,20,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [56]:
arr = np.arange(10,0,-1)
arr

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [57]:
arr = np.linspace(0,10,20) #ye ziada tar fack data k liye use hota h.starting point 0, 
                             #10 number of value, 20 har value ko
                               # barabar barabar parts me tor (break) kr de ga 
arr

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [ ]:
# shape of matrix 
shape(2,4)
# first element show of number of row 
# second element show of number of column


In [58]:
# shape of vactor 
#shape(4,) (,) one array yani vactor ko show krta h
#is (,) ka matlab h 4 element aur one row h  

In [59]:
a = np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [64]:
b = np.empty(8)
b

array([0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 6.50190390e-321, 8.01097888e-307, 1.42419530e-306])

In [68]:
 # np.full matlub eye identity
#eye.identity  

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [69]:
#mathod 2
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [71]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [74]:
np.identity(2,3)

TypeError: data type not understood

In [75]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [80]:
np.eye(2,5,  dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0]])

In [77]:
np.eye(2,2,  dtype=float)


array([[1., 0.],
       [0., 1.]])

In [87]:
np.full((2,2,2),[1,2])

array([[[1, 2],
        [1, 2]],

       [[1, 2],
        [1, 2]]])

In [115]:
def function16():
    #Write a NumPy program to join a sequence of arrays along depth.
    
    
    x = np.array([[1], [2], [3]])
    y = np.array([[2], [3], [4]])
    ans = np.dstack([x,y])#write your code here 
  
    return ans

    """
     Expected Output:
                [[[1 2]]

                 [[2 3]]

                 [[3 4]]]
     """ 
    
print(function16())

[[[1 2]]

 [[2 3]]

 [[3 4]]]


# Expicitly convert / cast data type of array


In [121]:
int_arr = np.array([100,200,300,400,500])
int_arr

array([100, 200, 300, 400, 500])

In [120]:
int_arr.dtype

dtype('int32')

In [122]:
int_arr.astype(np.float64)

array([100., 200., 300., 400., 500.])

In [123]:
int_arr.astype(int)

array([100, 200, 300, 400, 500])

In [126]:
int_arr.astype(float)

array([100., 200., 300., 400., 500.])

In [127]:
int_arr.dtype

dtype('int32')

In [130]:
a = int_arr.astype(float)
a

array([100., 200., 300., 400., 500.])

In [131]:
a.dtype

dtype('float64')

In [133]:
int_arr.dtype

dtype('int32')

In [141]:
arr = np.array([1.5,5.6,2,3.9,7.4]) # agr hum float ko int m convert kry gy to point k bad ki value khatm ho jai gi
arr

array([1.5, 5.6, 2. , 3.9, 7.4])

In [138]:
arr2 = arr.astype(np.int32)
arr2

array([1, 5, 2, 3, 7])

In [139]:
# method 2
arr1 = arr.astype(int)
arr1

array([1, 5, 2, 3, 7])

In [140]:
arr1.dtype

dtype('int32')

# Arithmetic with numpy Array

In [152]:
a1 = np.arange(10,20)
a1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [153]:
a1 * 4

array([40, 44, 48, 52, 56, 60, 64, 68, 72, 76])

In [154]:
a2 = np.arange(0,10)
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [158]:
a2 + a1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [159]:
a1 + a2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [160]:
a1 - a2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [161]:
a2 - a1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [162]:
a1 /2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [166]:
a2 /1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

# Accessing 1-D Array


In [2]:
import numpy as np
a1 = np.arange(1,11)
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
a1[0]

1

In [4]:
a1[-1]

10

In [5]:
a1[1],a1[5]

(2, 6)

In [16]:
a1[1:7]

array([2, 3, 4, 5, 6, 7])

In [17]:
a1[1], a1[7]

(2, 8)

In [19]:
a1[2:6]

array([3, 4, 5, 6])

In [21]:
a1[0][5]

IndexError: invalid index to scalar variable.

In [190]:
# Accessing 2-d Array 
arr3 = np.array([[1,2,3,4,5,6,],[11,22,33,44,55,66]])
arr3

array([[ 1,  2,  3,  4,  5,  6],
       [11, 22, 33, 44, 55, 66]])

In [191]:
arr4 = np.arange(20).reshape(4,5)
arr4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [192]:
np.size(arr3)

12

In [193]:
np.size(arr4)

20

In [194]:
np.size(arr4,0)  # matlb row kitni hein

4

In [196]:
np.size(arr4,1) # mtlb column kitny hein

5

In [197]:
arr4.shape # 4 row aur 5 column hain is trha hum at a time row and column dekh skty hain

(4, 5)

# Reshape se 1-d array ko 2 & 3 d array m convert kr skty hain aur 2d array ko 1-d m convert krskty hain 

In [200]:
arr4 = np.arange(0,20).reshape(4,5)
arr4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [199]:
arr1 = arr4.reshape(20)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [202]:
arr2 = np.arange(64).reshape(8,8) # 8 row , 8 column
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [204]:
arr2 = np.arange(64).reshape(8,4,2) # 8 depth, 4 row, 2 columns
arr2

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]],

       [[32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47]],

       [[48, 49],
        [50, 51],
        [52, 53],
        [54, 55]],

       [[56, 57],
        [58, 59],
        [60, 61],
        [62, 63]]])

In [206]:
arr2 = np.arange(64).reshape(2,4,8) # 2 depth, 4 rows, 8 columns
arr2

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31]],

       [[32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62, 63]]])

In [207]:
arr2 = np.arange(64).reshape(4,4,4) # 4 depth, 4 row, 4 columns
arr2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

# Ravel()
# is k through hum multy martix ko 1-D array ya vactor m convert kr skty hain. 

# np.ravel()
# it is directly convert the array to 1d only array 

# Difference between into np.ravel & np.reshape

# np.ravel() high dimension array ko 1-d array m convert krta h 

# np.reshape ye high dimension array ko 1d array convert krtha h aur 1d ko high dimension m convert krta h 

# reshape ya ravel k thourgh hum array m jo change laty hain wo view k sth sath humary original array m b change krta h yani ye copy ni krta direct original ko convert krta h  


In [217]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [220]:
arr1[0] = 888
arr1

array([[888, 888, 888],
       [  3,   4,   5],
       [  6,   7,   8]])

In [221]:
arr1

array([[888, 888, 888],
       [  3,   4,   5],
       [  6,   7,   8]])

# Flatten
ye be 1d m convert krta h view krta magr original array ki copy bnaleta h 

In [46]:
a = np.arange(25,0,-1).reshape(5,5)
a

array([[25, 24, 23, 22, 21],
       [20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [49]:
flattened_ab= a.flatten()
flattened_ab

array([25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,
        8,  7,  6,  5,  4,  3,  2,  1])

In [50]:
flattened_ab[1]=55
flattened_ab


array([25, 55, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,
        8,  7,  6,  5,  4,  3,  2,  1])

In [51]:
a

array([[25, 24, 23, 22, 21],
       [20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [52]:
flattened_a = a.flatten()
flattened_a

array([25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,
        8,  7,  6,  5,  4,  3,  2,  1])

In [53]:
flattened_a[1]=66
flattened_a

array([25, 66, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,
        8,  7,  6,  5,  4,  3,  2,  1])

In [54]:
flattened_a

array([25, 66, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,
        8,  7,  6,  5,  4,  3,  2,  1])

In [55]:
a

array([[25, 24, 23, 22, 21],
       [20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [37]:
b = np.arange(20,0,-1).reshape(4,5)
b

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [39]:
c = b.flatten()
c

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1])

In [40]:
b

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [41]:
c

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1])

In [43]:
c[3]=45
c

array([20, 19, 18, 45, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1])

In [44]:
b

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

# np.resize() is danger

In [ ]:
# agr hum resize k method ko use kia to humara all data reshape ho jaye ga 
original data reshape ho jay ga 

In [56]:
x = np.arange(25,0,-1).reshape(5,5)
x

array([[25, 24, 23, 22, 21],
       [20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [65]:
y = x.resize(1,25)# is varibal m humara data show ni ho ga is k liye original varibal ko
                     #call krna ho ga jaha all data 
                    #reshape ho choka h 
y

In [66]:
x

array([[25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,
         9,  8,  7,  6,  5,  4,  3,  2,  1]])

# Basic indexing & Slicing of Multi dimensional array 

In [67]:
ar2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
ar2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# indexing

In [68]:
ar2d[1]          # row 2 show ho gi  # agr esy likhy gy to row ki indexing kre ga

array([5, 6, 7, 8])

# accesing a complete columns

In [69]:
ar2d[:,1]   # column 2 show ho ga [: row show],[1 show column] 

array([ 2,  6, 10])

In [90]:
d2 = np.arange(1,26).reshape(5,5)
d2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [91]:
d2[3,3]

19

In [92]:
d2[3][3]

19

In [82]:
d2[1][4]

10

In [83]:
d2.shape

(5, 5)

In [85]:
d2[0,3],d2[1,2],d2[2,4],d2[4,1],d2[3,3]

(4, 8, 15, 22, 19)

# Structure for indexing & slicing in a 2d array

In [ ]:
# shape (Row,Column)
#       (------------:----------,--------------:------------)  
#       (start of row:end of row,start of colum:end of colum)

In [93]:
d2[0:3,1:1]

array([], shape=(3, 0), dtype=int32)

In [94]:
d2[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [100]:
a = np.arange(26,51).reshape(5,5)
a

array([[26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [105]:
a[0:4,1:2]

array([[27],
       [32],
       [37],
       [42]])

In [106]:
a[0:5,0:3]

array([[26, 27, 28],
       [31, 32, 33],
       [36, 37, 38],
       [41, 42, 43],
       [46, 47, 48]])

In [107]:
a[1:,0:3]

array([[31, 32, 33],
       [36, 37, 38],
       [41, 42, 43],
       [46, 47, 48]])

In [108]:
a[0:2,3:]

array([[29, 30],
       [34, 35]])

In [109]:

# OR
a[0:2,3:5]

array([[29, 30],
       [34, 35]])

In [110]:

OR
a[0:2,-2:]

array([[29, 30],
       [34, 35]])

# indexing
targit the element of the array the returned is the individual value or group of values haing  thier own data type.
matlb element ya element of group dimension less hoty. 



In [111]:
a[4][2]  # indexing h ye . 48 ki koi dimension ni h jb k hum ne 2d array create ki thi

48

# Slicing     


In [112]:
a[4:,2:3]    # 48 yaha humary pass 2d array h 

array([[48]])

# Difference between into indexing & slicing

In [ ]:
indexing m hum kisi value ya value of group ko uthaty hain to wo is ko element shape m uthata h  
jis ki apni alag data type 
hogi (indexing returneds & targit element of array )
jab k slicing m hum kisi b value ko array ki shape m uthay gay. slicing us waqt tk slicing
rahy gi jab tak hum Row & Columns
k all paramiters ko use krty hn. jis expression m four values pass ki jain chay empty q na ho
(:2,1:)


In [120]:
a[:2,1:]


array([[27, 28, 29, 30],
       [32, 33, 34, 35]])

In [121]:
a[:2,1:].shape

(2, 4)

In [122]:
#Expression (answer vactor ki shakal m aye ga)
a[2]

array([36, 37, 38, 39, 40])

In [123]:
a[2].shape

(5,)

In [124]:
a[2,:]

array([36, 37, 38, 39, 40])

In [125]:
a[2,:].shape

(5,)

In [132]:
a[0:,:]

array([[26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [131]:
a[0:,:].shape

(5, 5)

In [133]:
a[4,2:3]   # indexing h ye 

array([48])

In [135]:
a[4:,2:3]  #slicing h ye 

array([[48]])

In [136]:
a[1:4,0:]  #slicing

array([[31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45]])

In [137]:
a[2:3,0]  # indexing 

array([36])

In [138]:
a[1:4,2]    #indexing 

array([33, 38, 43])

In [139]:
a[1:4,:3]   #slicing 

array([[31, 32, 33],
       [36, 37, 38],
       [41, 42, 43]])

In [ ]:
n